### teste delogin 
POST http://localhost:40000/Login HTTP/1.1
Content-Type: application/json

{
    "username": "qwe", 
    "password": "qwe"
}

### teste de logout 
POST http://localhost:40000/Logout HTTP/1.1
Content-Type: application/json

{

}