### Necessário para pegar o token
### Post
# @name loginAutenticado
POST http://localhost:40000/Login HTTP/1.1
content-type: application/json

{
    "username": "qwe",
    "password": "qwe"
}
### Seta o token
@accessToken = {{loginAutenticado.response.body.$.token}}

### Teste de inserção de produto
POST http://localhost:40000/insertPedidos HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "numero": "5",
    "data": "2022-03-02",
    "valortotal": 450,
    "clienteid": 1,
    "deleted": false
}

### Teste de buscar todos os produtos
GET http://localhost:40000/getAllPedidos HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

### Teste de buscar produto por ID
POST http://localhost:40000/getPedidoByID HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "pedidoid": 1
}

### Teste de atualização de produto
POST http://localhost:40000/updatePedidos HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "pedidoid": 1,
    "numero": "06",
    "data": "2022-03-04",
    "valortotal": 450.02,
    "clienteid": 1,
    "deleted": false
}

### Teste de exclusão (soft delete) de produto
POST http://localhost:40000/deletePedidos HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "pedidoid": 2
}